In [2]:
import joblib
import kagglehub
import modin.pandas as pd
from utils import preprocess_data

# Load dataset (example: historical ticket pricing data)
path = kagglehub.dataset_download("ibrahimelsayed182/plane-ticket-price")
print("Path to dataset files:", path)
data_path = fr'{path}\ticket_pricing_data.csv'
raw = pd.read_csv(r'C:\Users\Alex\.cache\kagglehub\datasets\ibrahimelsayed182\plane-ticket-price\versions\1\Data_Train.csv')

c:\Projects\datasci2\DataSci\.ml\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Path to dataset files: C:\Users\Alex\.cache\kagglehub\datasets\ibrahimelsayed182\plane-ticket-price\versions\1

In [3]:
raw.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [4]:
#select the flights form Kolkata to Banglore
data = raw[raw['Source'] == 'Kolkata']
data = data[data['Destination'] == 'Banglore']
data.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
5,SpiceJet,24/06/2019,Kolkata,Banglore,CCU → BLR,09:00,11:25,2h 25m,non-stop,No info,3873
11,IndiGo,18/04/2019,Kolkata,Banglore,CCU → BLR,20:20,22:55,2h 35m,non-stop,No info,4174
13,Jet Airways,9/05/2019,Kolkata,Banglore,CCU → BOM → BLR,21:10,09:20 10 May,12h 10m,1 stop,In-flight meal not included,9663

In [5]:
#select fligths with a durateion between 6 and 8 hours
data2 = raw[raw['Duration'] >= '6h']
data2 = data2[data2['Duration'] <= '8h']
#get the average price of the flights
average_price = data2['Price'].mean()
print(average_price)

11455.806703910615

In [6]:
# Load the label encoders and scaler (if used during preprocessing)
label_encoders = joblib.load(r'C:\Projects\datasci2\DataSci\ML\TicketPrice\live_model\model_outputs\label_encoders.pkl')
scaler = joblib.load(r'C:\Projects\datasci2\DataSci\ML\TicketPrice\live_model\model_outputs\scaler.pkl')

In [7]:
def preprocess_input_data(input_data, label_encoders, scaler):
    # Assume the preprocess_data function handles necessary preprocessing steps
    X_new, y, label_encoders, scaler = preprocess_data(input_data, label_encoders, scaler)
    return X_new

In [8]:
X_processed = preprocess_input_data(raw, label_encoders, scaler)

Warning: There are NaN values in the 'Total_Stops' column after mapping.

In [10]:
X_processed.head(50)

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Journey_day,Journey_month,Dep_hour,Dep_minute,Arrival_hour,Arrival_minute
0,3,0,5,18,1.237383,0,8,-1.467490,1.654259,-0.235050,-1.800427,-0.890057,-0.931583
1,1,3,0,84,-1.475239,2,8,0.250276,-1.303095,1.363492,-0.050851,-0.587124,-0.390072
2,4,2,1,118,-0.531719,2,8,1.109160,-0.607247,0.031373,-1.363033,0.018744,0.978475
3,3,3,0,91,-0.177898,1,8,0.250276,0.958411,-1.034321,1.407129,0.321677,-0.626367
4,3,0,5,29,-1.475239,1,8,-1.467490,0.610487,1.363492,1.115533,0.624611,-0.705132
5,8,3,0,64,1.237383,0,8,1.109160,-0.607247,-1.300745,-0.342447,0.018744,-0.980811
6,4,0,5,5,-0.177898,1,5,-1.467490,0.958411,1.629915,-0.488245,0.018744,0.564957
7,4,0,5,5,-1.475239,1,8,-1.467490,-0.781209,-1.300745,-1.217235,-1.192991,1.224616
8,4,0,5,5,-0.177898,1,5,-1.467490,-0.781209,1.629915,-0.488245,0.018744,1.746436
9,6,2,1,104,1.591203,1,8,0.250276,-0.259323,0.031373,0.823937,-0.587124,-0.340843
10,1,2,1,103,-1.475239,1,8,1.109160,-0.607247,1.097068,1.407129,-1.495925,0.299124
11,3,3,0,64,0.529742,0,8,-0.608607,1.306335,-0.235050,1.261331,1.836346,-0.961120
12,1,1,4,127,1.237383,0,8,1.109160,-0.259323,0.830644,-0.050851,1.836346,-1.000502
13,4,3,0,66,-0.531719,1,5,0.250276,1.480297,-0.767898,-0.634043,-0.284190,0.171131
14,3,3,0,64,1.237383,0,8,-0.608607,0.784449,-0.501474,0.823937,1.533412,-0.961120
15,1,2,1,97,-1.239359,2,8,-1.467490,0.610487,0.830644,0.823937,-0.587124,1.874429
16,8,2,1,123,0.175922,1,8,-0.608607,-0.781209,1.097068,-0.050851,-0.587124,-0.734669
17,4,2,1,104,-0.177898,1,5,1.109160,0.262563,-1.300745,-0.196649,0.624611,1.401838
18,1,2,1,105,-0.177898,2,8,1.109160,1.306335,-0.501474,0.823937,-0.587124,1.451066
19,4,2,1,104,1.591203,1,5,0.250276,0.610487,-1.300745,-0.196649,0.624611,1.165542
20,2,2,1,104,-0.885539,1,8,-1.467490,0.262563,-0.767898,0.823937,-0.284190,-0.655904
21,1,0,5,17,0.883563,1,8,-1.467490,1.654259,-1.300745,-0.050851,-0.284190,0.545266
22,3,0,2,18,-1.239359,0,8,-0.608607,-1.477057,-1.300745,-1.071437,1.533412,-0.931583
23,3,0,2,18,-1.475239,0,8,0.250276,0.958411,1.629915,1.115533,1.533412,-0.921737
24,4,3,0,66,-0.885539,1,5,0.250276,0.958411,1.629915,-0.779841,-0.587124,0.308970
25,4,2,1,113,-0.531719,2,8,1.109160,1.480297,0.031373,-0.196649,0.624611,0.525574
26,3,2,1,119,-1.475239,1,8,1.109160,1.480297,1.363492,-1.508831,0.624611,-0.586985
27,2,2,1,104,0.175922,1,8,0.250276,-0.955171,-1.300745,-0.196649,1.836346,-0.567293
28,10,0,2,18,0.529742,0,8,1.109160,-0.607247,1.097068,-0.196649,0.624611,-0.931583
29,10,1,4,127,0.175922,0,8,1.109160,-0.955171,-1.034321,-0.634043,-0.284190,-1.000502
30,10,1,4,127,0.529742,0,8,1.109160,-0.955171,-1.034321,-0.634043,-0.284190,-1.000502
31,1,3,0,78,-1.475239,2,8,0.250276,-0.607247,1.363492,1.407129,-0.587124,0.318816
32,3,0,2,18,-0.885539,0,8,-0.608607,-1.477057,-1.300745,-1.071437,1.533412,-0.931583
33,4,2,1,122,0.175922,2,5,1.109160,0.262563,0.564221,-0.196649,0.624611,1.332918
34,4,2,1,104,0.529742,1,5,0.250276,-0.955171,-1.034321,-0.196649,0.624611,-0.616522
35,3,2,1,104,1.591203,1,8,1.109160,-0.433285,0.564221,1.115533,-1.495925,-0.035628
36,8,3,0,90,0.883563,1,8,0.250276,0.436525,-1.034321,0.969735,-0.284190,-0.646059
37,1,3,0,64,0.529742,0,8,0.250276,0.262563,-0.501474,0.386543,1.230478,-0.970965
38,4,0,5,5,-0.885539,1,8,-1.467490,-0.955171,-1.300745,-0.050851,-0.587124,-0.527911
39,4,2,1,104,-1.239359,1,8,1.109160,-0.955171,-1.034321,0.823937,-1.495925,0.141594
40,6,2,1,111,0.883563,1,8,0.250276,-0.955171,-1.034321,0.678139,-0.890057,0.043137
41,1,0,5,5,0.175922,1,8,-1.467490,-1.129133,1.097068,0.240745,-0.587124,-0.262078
42,4,2,1,104,0.529742,1,5,0.250276,1.306335,1.629915,0.823937,-1.495925,1.342764
43,0,0,2,18,-0.885539,0,8,0.250276,-0.259323,-0.767898,-0.050851,1.836346,-0.941428
44,6,2,1,104,0.883563,1,8,-1.467490,-0.607247,-1.300745,1.115533,-1.495925,0.151440
45,8,0,5,18,1.237383,0,7,-1.467490,-1.303095,1.097068,-0.779841,0.624611,-0.931583
46,3,0,2,18,1.591203,0,8,0.250276,-1.477057,-1.300745,-1.071437,1.533412,-0.931583
47,1,1,4,127,-1.239359,0,8,0.250276,-0.259323,0.830644,-0.050851,1.836346,-1.000502
48,1,3,0,80,0.175922,1,8,0.250276,1.132373,-1.300745,-0.342447,-1.192991,0.633877
49,4,2,1,97,1.591203,2,5,1.109160,1.828221,-1.034321,0.823937,-1.495925,1.086777

TypeError: unsupported operand type(s) for /: 'float' and 'str'

TypeError: unsupported operand type(s) for /: 'float' and 'str'